# Generated by Django 4.1.2 on 2023-12-04 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='ユーザー名')),
                ('job_title', models.CharField(max_length=255, verbose_name='仕事タイトル')),
                ('job_detail', models.CharField(max_length=1000, verbose_name='仕事詳細')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
        ),
    ]
